version: '3'

services:
  db:
    image: postgres
    container_name: db_avito
    environment:
      POSTGRES_DB: pgdb_avito
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    network_mode: bridge

  server:
    build: .
    image: avito:lastest
    container_name: server_avito
    ports:
      - "6000:6000"
    network_mode: bridge
    depends_on:
      - db